### ISSUE TITLE
1146 Table 'suriyaakudo_myw.oauth_accepted_consumer' doesn't exist (localhost)

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [mywikibp/gh-phabricator#2]
> This issue is reported at Wikimedia Phabricator: https://phabricator.wikimedia.org/T122809!

----

After debugging my wiki I got an debug output in `Special:Preferences` site (link: http://suriyaakudo.bplaced.net/w/index.php?title=Special:Preferences / I disabled SQL debugging again):

----

* Request:
```
SELECT COUNT(*) FROM `oauth_accepted_consumer`,`oauth_registered_consumer` WHERE (oaac_consumer_id = oarc_id) AND oaac_user_id = '1' AND oarc_deleted = '0' LIMIT 1 
```

* Function: 
```
MediaWiki\Extensions\OAuth\MWOAuthUIHooks::onGetPreferences
```

* Error: 
```
1146 Table 'suriyaakudo_myw.oauth_accepted_consumer' doesn't exist (localhost)
```

* Backtrace:

```
#0 /users/suriyaakudo/www/w/includes/db/Database.php(1205): DatabaseBase->reportQueryError('Table 'suriyaak...', 1146, 'SELECT  COUNT(*...', 'MediaWiki\\Exten...', false)
#1 /users/suriyaakudo/www/w/includes/db/Database.php(1726): DatabaseBase->query('SELECT  COUNT(*...', 'MediaWiki\\Exten...')
#2 /users/suriyaakudo/www/w/includes/db/Database.php(1394): DatabaseBase->select(Array, 'COUNT(*)', Array, 'MediaWiki\\Exten...', Array)
#3 [internal function]: DatabaseBase->selectField(Array, 'COUNT(*)', Array, 'MediaWiki\\Exten...')
#4 /users/suriyaakudo/www/w/includes/db/LoadBalancer.php(1276): call_user_func_array(Array, Array)
#5 /users/suriyaakudo/www/w/extensions/v1.25/OAuth/frontend/MWOAuthUI.hooks.php(29): DBConnRef->__call('selectField', Array)
#6 /users/suriyaakudo/www/w/extensions/v1.25/OAuth/frontend/MWOAuthUI.hooks.php(29): DBConnRef->selectField(Array, 'COUNT(*)', Array, 'MediaWiki\\Exten...')
#7 [internal function]: MediaWiki\Extensions\OAuth\MWOAuthUIHooks::onGetPreferences(Object(User), Array)
#8 /users/suriyaakudo/www/w/includes/Hooks.php(209): call_user_func_array('MediaWiki\\Exten...', Array)
#9 /users/suriyaakudo/www/w/includes/Preferences.php(99): Hooks::run('GetPreferences', Array)
#10 /users/suriyaakudo/www/w/includes/Preferences.php(1259): Preferences::getPreferences(Object(User), Object(RequestContext))
#11 /users/suriyaakudo/www/w/includes/specials/SpecialPreferences.php(60): Preferences::getFormObject(Object(User), Object(RequestContext))
#12 /users/suriyaakudo/www/w/includes/specialpage/SpecialPage.php(384): SpecialPreferences->execute(NULL)
#13 /users/suriyaakudo/www/w/includes/specialpage/SpecialPageFactory.php(582): SpecialPage->run(NULL)
#14 /users/suriyaakudo/www/w/includes/MediaWiki.php(267): SpecialPageFactory::executePath(Object(Title), Object(RequestContext))
#15 /users/suriyaakudo/www/w/includes/MediaWiki.php(566): MediaWiki->performRequest()
#16 /users/suriyaakudo/www/w/includes/MediaWiki.php(414): MediaWiki->main()
#17 /users/suriyaakudo/www/w/index.php(41): MediaWiki->run()
#18 {main}
```

I add at the end of the `LocalSettings.php` file this code:

```
$wgShowSQLErrors = true;
$wgDebugDumpSql  = true;
$wgShowDBErrorBacktrace = true;
```

![Datenbankfehler in MyWiki Special:Preferences](https://phab.wmfusercontent.org/file/data/hm65tvtbx7pw6wprdi3a/PHID-FILE-luouou4tbrubi75t645l/FireShot_Screen_Capture_024_-_Datenbankfehler_%E2%80%93_MyWiki_-_suriyaakudo_bplaced_net_w_index_php_title_Special_Preferences.png)

> What's the problem?

----

I use:

* MediaWiki 1.25.2
* PHP 5.5.21 (cgi-fcgi)
* MariaDB 5.5.33a-MariaDB
* Lua 5.1.5

----

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by SuriyaaKudoIsc** [comment]
> ***Solution:*** Disabled **`OAuth`** *extension* for MyWiki completely.
